import prisma from './db';
import bcrypt from 'bcryptjs';

const GLOBAL_SECTIONS = ['InfoBar', 'Navbar', 'Footer'];
const HOME_SECTIONS = [
  'Hero', 'ModernHero', 'Services', 'AboutUs', 'SearchCourses', 'PopularCourses', 'CoursesGrid',
  'Achievements', 'UpcomingEvents', 'CourseCategories', 'WhyChooseUs', 'Team',
  'CTA', 'PricingPlan', 'LatestNews', 'Testimonials', 'Partners', 'Instagram',
  'Video', 'Products'
];
const ABOUT_SECTIONS = [
  'Breadcrumbs', 'AboutHistory', 'AboutMission', 'AboutVision', 'AboutTimeline', 'AboutBranches',
  'Team', 'CTA', 'Partners'
];
const CONTACT_SECTIONS = ['Breadcrumbs', 'ContactSection', 'Partners'];

function getContent(type: string, pageContext: string) {
  if (type === 'InfoBar') return { phone: '+1 123 456 7890', email: 'info@edulearn.com', address: '503 Old Buffalo Street', showSocials: true, welcomeText: 'Welcome to Electricity' };
  if (type === 'Navbar') return { 
    logos: [
      { url: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777020185/educa/yjo89dqvujzjtrqey5bv.png" },
      { url: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777020129/educa/llflhw7qn40vncck2sn1.png" }
    ],
    navItems: [
      { label: 'About CC Electricity', href: '/about' },
      { label: 'Programs', href: '/services' },
      { label: '7 CORE FEATURES', href: '/core-features' },
      { label: '5 Significant Advances', href: '/five-significant-advances' },
      { label: 'Contact', href: '/contact' }
    ], 
    showSearch: true 
  };
  if (type === 'Footer') return { 
    copyright: '© 2026 Edulearn. All Rights Reserved.', 
    aboutText: 'Electricity platform.', 
    aboutText2: 'We specialize in sales and delivery of all electrical services.',
    copyrightText: '© 2026 Electricity. All Rights Reserved.',
    newsletterTitle: 'Newsletter',
    showRecentPosts: false
  };
  
  if (type === 'Hero') return { slides: [{ image: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777019777/educa/kndwz1rx6uh90lnnwril.png", title: "WELCOME", desc: "Compassionate Capitalism Electricity", showTitle: true, showDesc: true, showBtn1: true, btn1Text: "READ MORE", btn1Link: "#" }] };
  if (type === 'ModernHero') return {
    title: "The Future of electricity",
    subtitle: "Welcome to Compassionate Capitalism",
    desc: "Electricity powers modern life, yet remains out of reach for millions. We’re driving inclusive access through innovation, investment, and sustainable solutions.\n",
    image: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777357063/educa/eibzivusgptrtxiesudf.png",
    btnText: "Get Started",
    btnLink: "#"
  };
  if (type === 'AboutUs') return { 
    title: 'ABOUT US', 
    subtitle: 'The best provider', 
    text: 'We provide high quality education.', 
    desc: 'The Compassionate Catalyst for Change',
    image: 'https://res.cloudinary.com/e-commerce-website/image/upload/v1777466947/educa/wwvrfzajk9fodpka6ji5.png',
    items: [
      {
        id: "history",
        title: "Our History",
        body: "Electricity, the energy generated by charged particles, has become essential to modern life—powering homes, industries, healthcare, and social activities. Despite its importance, access remains unequal, with many communities still living without reliable electricity due to uneven global development driven by market systems."
      },
      {
        id: "mission",
        title: "Our Mission",
        body: "To expand access to electricity for marginalized communities by promoting knowledge, enabling capital investment, supporting fair trade, advocating for favorable policies, and delivering innovative energy solutions."
      },
      {
        id: "vision",
        title: "Our Vision",
        body: "A world where electricity is universally accessible, driving inclusive development, improving quality of life, and supporting sustainable progress through compassionate and equitable economic systems."
      }
    ]
  };
  if (type === 'Services') return { title: 'OUR SERVICES', items: [] };
  if (type === 'ContactSection') return { 
    mapUrl: "https://www.google.com/maps/embed?pb=!1m18", 
    addressLines: ["503 Old Buffalo Street"], phones: ["+123"], emails: ["info@example.com"],
    showMap: true, showAddress: true, showPhone: true, showEmail: true, showForm: true 
  };
  if (type === 'Breadcrumbs') return { 
    title: pageContext.toUpperCase(), 
    crumbs: [{ label: 'Home', href: '/' }, { label: pageContext, href: '#' }],
    backgroundImage: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777020958/educa/oyf3ghkdq9225bzhupl5.png"
  };

  if (type === 'CoursesGrid') return {
    title: "OUR PROGRAMS",
    description: "We specialize in sales and delivery of all electrical services",
    viewMoreText: "View All",
    viewMoreLink: "/services",
    courses: [
      { title: "Electric wires", category: "Service", desc: "Sales of electric wires and gadgets", img: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777028980/educa/syaqvmzvp3d8lywibgqq.png" },
      { title: "Solar system installations", category: "Course", desc: "Learn solar installations", img: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777029088/educa/gyzr7dfyiiz0xw6wvkza.png" },
      { title: "Lithum Ion Bateries", category: "Sales", desc: "We deal with the sales of solar batteries", img: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777029177/educa/mn1brgdzjppvralrrdcl.png" }
    ]
  };

  if (type === 'Testimonials') return {
    title: "TESTIMONIALS",
    subtitle: "What our clients and partners are saying",
    bgImage: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777029583/educa/ilfckjjssryauktnjhjm.png",
    testimonials: [
      { name: "Favour Ngozi", text: "Great learning experience!", img: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777029636/educa/u3ekfutktmegjjkqiaec.png" },
      { name: "Faith Abraham", text: "I learnt a lot and it was really worth it", img: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777030095/educa/vjnipifjudmgzzfkqeg9.png" }
    ]
  };

  if (type === 'Partners') return {
    title: "PARTNERS",
    partners: [
      { img: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777370703/educa/ges8rlufwem2pj6rzlfr.png", link: "#" },
      { img: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777370717/educa/gqy3lgdxdfgjfqnsfun3.png", link: "#" },
      { img: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777370747/educa/ylcvtob2juuil6qxkmx4.png", link: "#" }
    ]
  };

  if (type === 'Video') return {
    title: "VIDEO",
    label: "GET TO KNOW US",
    bgImage: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777370168/educa/bws5yj1kmixx0mqnbdan.png",
    videoUrl: "https://vimeo.com/1095624426?fl=pl&fe=cm"
  };
  
  return { title: type.toUpperCase() };
}

async function main() {
  console.log('🌱 Baseline seeding for CMS...');
  
  // 1. Admin account
  const existingAdmin = await prisma.admin.findUnique({ where: { username: 'admin' } });
  if (!existingAdmin) {
    const hashed = await bcrypt.hash('admin123', 10);
    await prisma.admin.create({ data: { username: 'admin', password: hashed } });
    console.log('✅ Created admin (admin/admin123)');
  }

  // 2. SiteConfig
  const existingConfig = await prisma.siteConfig.findUnique({ where: { id: 'default-config' } });
  if (!existingConfig) {
    await prisma.siteConfig.create({
      data: {
        id: 'default-config',
        layoutType: 'home1',
        siteTitle: 'Compassionate Capitalism Electricity',
        colors: { primary: "#6bb2f5", secondary: "#052266", bg: "#ffffff", text: "#000000" }
      }
    });
    console.log('✅ Created default config');
  }

  // 3. Pages and Sections
  const pagesData = [
    { name: 'Home', slug: '/', sections: ['InfoBar', 'Navbar', 'ModernHero', 'Hero', 'Services', 'AboutUs', 'SearchCourses', 'PopularCourses', 'CoursesGrid', 'Achievements', 'UpcomingEvents', 'CourseCategories', 'WhyChooseUs', 'Team', 'CTA', 'PricingPlan', 'LatestNews', 'Testimonials', 'Partners', 'Instagram', 'Video', 'Footer', 'Products'] },
    { name: 'About Us', slug: '/about', sections: ['InfoBar', 'Navbar', 'Breadcrumbs', 'AboutHistory', 'AboutMission', 'AboutVision', 'AboutTimeline', 'AboutBranches', 'Team', 'CTA', 'Partners', 'Footer'] },
    { name: 'Contact Us', slug: '/contact', sections: ['InfoBar', 'Navbar', 'Breadcrumbs', 'ContactSection', 'Partners', 'Footer'] },
    { 
      name: 'Core Features', 
      slug: '/core-features', 
      sections: [
        { type: 'Infobar', isVisible: false },
        { type: 'Navbar' },
        { type: 'Hero', isVisible: false },
        { 
          type: 'FeaturesHero', 
          content: {
            title: "7 Core Features of Compassionate Capitalism",
            bgImage: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777225547/educa/yzx738vitcidhr9tdybr.png",
            tagline: "The Path to Global Prosperity",
            description: "Redirecting global commerce to meet the Creator’s original intent for humanity through a just and empathetic economic framework."
          }
        },
        {
          type: 'FeaturesGrid',
          content: {
            items: [
              { id: 1, title: "INVESTMENT POINTS", description: "Graze the cow you milk by ensuring that all purchases for goods or services are rewarded with a discount in cost which is given as Investment Points and can be used by the consumer to make investments in need based commercial projects for returns or in career building through certificates to earn." },
              { id: 2, title: "28 NEED BASED SECTORS", description: "Prioritize access to 28 basic human needs for all before any further aspirations, promoting contentment as a core value and empathy driven investments as the new norm with triple bottom-line pursuits of finance, social good and environment." },
              { id: 3, title: "DEVELOPMENT RANKINGS", description: "Coordinate unbiased measurement and public reporting of access to the 28 basic human needs for each segment of the world in comparison to a more developed region, highlighting areas of deficiency for investments, policy formulation and public rally." },
              { id: 4, title: "DEMOCRATIC ECONOMY", description: "Reduce and eradicate market monopoly and economic imperialism through local production support and local producer’s market guarantee through the implementation of a democratic economy that promotes market of the people, by the people, for the people." },
              { id: 5, title: "ECONOMIC VALUE", description: "Organize and strengthen the labour market through promotion of economy focussed educational system, skill acquisition and character centred individual capacity building, measurement and reward that eliminates favouritism, nepotism, tribalism and mediocrity in labour contribution to the production process." },
              { id: 6, title: "TRINITY ACCOUNTS", description: "Structure and Implement a triple financial accounts system that involves expenditures through the Shopping Account, empowering the shopper through the Investment Points Account and receiving returns on investments through the Returns Account ensuring the absolute end of lack, poverty, despair and economic hopelessness." },
              { id: 7, title: "CONSUMER EDUCATION", description: "Prohibit the concept of make-belief in advertising and promote the education of consumers in all offers made by producers helping to eradicate exploitation, deception, fraud and even death of consumers." }
            ]
          }
        },
        {
          type: 'FeaturesQuote',
          content: {
            quote: "Through redirecting global commerce by implementing Compassionate Capitalism and its 7 core features, we will turn the earth to the kingdom of the God of Abraham and meet the Creator’s original intent for humanity.",
            author: "King Charles N. Lambert"
          }
        },
        { type: 'Footer' }
      ]
    },
    {
      name: 'Five significant advances',
      slug: '/five-significant-advances',
      sections: [
        { type: 'Infobar', isVisible: false },
        { type: 'Navbar' },
        {
          type: 'AdvancesHero',
          content: {
            title: "5 Significant Advances",
            tagline: "Evolution of Economics",
            introPara1: "While Capitalism works better than any other system in harnessing potential, there is a solid need to advance it without hampering innovation.",
            introPara2: "Compassionate Capitalism achieves this \"difficult oxymoron task,\" taking the economic system to a much higher place."
          }
        },
        {
          type: 'AdvancesList',
          content: {
            items: [
              { id: 1, title: "INDIVIDUALISM vs COMMUNAL GAIN", left: { label: "Individualism", content: "Capitalism believes that only individual gain can drive economic activities..." }, right: { label: "Communal Gain", content: "CC anchors on public enlightenment, educating the public that the safety of their prosperity lies in the well-being of their neighbors." } },
              { id: 2, title: "HIGHEST ASPIRATIONS vs CONTENTMENT", left: { label: "Highest Aspirations", content: "Chasing unreachable goals leads to greed, envy, and corruption..." }, right: { label: "Contentment", content: "Contentment is a sustainable catalyst for stiring..." } }
            ]
          }
        },
        {
          type: 'AdvancesAuthor',
          content: {
            title: "Created and Articulated by King Charles N. Lambert",
            tagline: "Institutional Innovation",
            description: "Economic visionary and innovator behind the Compassionate Capitalism movement."
          }
        },
        { type: 'Footer' }
      ]
    },
    {
      name: 'Investment Points',
      slug: '/investment-points',
      sections: [
        {
          type: 'FeaturesHero',
          content: {
            title: "Investment Points",
            tagline: " The World's Most Important Currency",
            description: "Discounts issued for regular consumer purchases that drive the accepted currency of the Global Compassionate Capitalism Investments Platform.",
            bgImage: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777231006/educa/x6qdvwqu5wabp9viwjlz.png"
          }
        },
        { type: 'Navbar' },
        {
          type: 'AdvancesHero',
          order: 1009,
          content: {
            title: "7 Key Benefits to the Modern World",
            introPara1: "As one of the 7 key aspects of the Compassionate Capitalism Economic System, IPs bring revolutionary benefits that address extreme poverty, unemployment, and developmental disparities."
          }
        },
        {
          type: 'FeaturesGrid',
          order: 1029,
          content: {
            items: [
              { id: 1, title: "Personal Investments Portfolio", description: "IPs are gained through regular consumer product purchases and do not carry the same level of risks for investments, encouraging every person in the world to build an interest-representing portfolio." },
              { id: 2, title: "Access to Business Capital", description: "IPs provide the 'important blood of capital' for starting and growing businesses, especially in less developed economies where traditional capital is difficult to obtain." }
            ]
          }
        },
        { type: 'Footer', order: 999 }
      ]
    },
    {
      name: 'Media Relations',
      slug: '/media-relations',
      sections: [
        { type: 'Infobar', isVisible: false },
        { type: 'Navbar' },
        {
          type: 'FeaturesHero',
          content: {
            title: "TV and Media Relations",
            tagline: "Media",
            description: "Banking TV and Media Relations provide information through the platform and you can access the platform by enrolling in one of the programs available in the industry.",
            bgImage: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777257134/educa/al6x5ot5ds145j2ergwq.png"
          }
        },
        {
          type: 'AdvancesHero',
          content: {
            title: "Protecting Public Trust in Information",
            introPara1: "One of the most abused tools in the world by free market capitalism is the media. The public’s trust in obtaining relevant life information from the media has instead been hijacked by corporate interests to feed them with propaganda, create hypes, deceive consumers and represents every other interest other than that of the naïve public.",
            introPara2: "Electricity TV and Media Relations is only concerned about the public and not corporate interests providing needed information on programs, public education, new technologies, innovations, jobs, professional certifications and other helpful tips that helps the public."
          }
        },
        { type: 'Footer', order: 999 }
      ]
    },
    {
      name: 'Development Rankings',
      slug: '/development-rankings',
      sections: [
        { type: 'Infobar' },
        { type: 'Navbar' },
        {
          type: 'FeaturesHero',
          content: {
            title: "Development Rankings",
            bgImage: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777262558/educa/ttz6hx5dmqmdglgmrv3h.png"
          }
        },
        {
          type: 'RichTextSection',
          content: {
            title: "Development Rankings",
            paragraphs: [
              "In the make believe world created by Free Market Capitalism, truth is a scarce commodity, data fictitious and facts obscure. This is a major hindrance to development and increasing access to basic human needs because measurement is the first process to change.",
              "Development Rankings is an initiative of the Compassionate Capitalism economic system and presents real life data submitted by real person surveys by certified investigative journalists working for the system across the world and through allocated job centres and jurisdictions."
            ]
          }
        },
        { type: 'Footer', order: 999 }
      ]
    },
    {
      name: 'The Mind of Charles N. Lambert',
      slug: '/mindset',
      sections: [
        { type: 'Infobar' },
        { type: 'Navbar' },
        {
          type: 'Breadcrumbs',
          content: {
            title: "The Mind of Charles N. Lambert",
            backgroundImage: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777432837/educa/nx3f0no2qe1dbkjrq9z1.png"
          }
        },
        {
          type: 'VideoGrid',
          content: {
            videos: [
              { title: "Understanding the BWS and Redirect Mall", videoUrl: "https://player.vimeo.com/video/863884866?h=f095ebbc64" },
              { title: "A risk-free way to become a shareholder", videoUrl: "https://player.vimeo.com/video/952202146?h=1ec69c3d2d" }
            ]
          }
        },
        { type: 'Footer', order: 999 }
      ]
    },
    {
      name: 'Services',
      slug: '/services',
      sections: [
        { type: 'Infobar', isVisible: false },
        { type: 'Navbar' },
        {
          type: 'FeaturesHero',
          content: {
            title: "Services",
            description: "We specialize in sales and delivery of all electrical services",
            bgImage: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777233391/educa/micbn1x3h50dbjeh4i9x.png"
          }
        },
        { type: 'CoursesGrid' },
        { type: 'Footer', order: 999 }
      ]
    },
    {
      name: 'Terms',
      slug: '/terms',
      sections: [
        { type: 'Infobar' },
        { type: 'Navbar' },
        {
          type: 'FeaturesHero',
          content: {
            title: "User Terms",
            tagline: "Transparency You Can Trust",
            description: "Review the terms that govern your use of our platform, including your rights, responsibilities, and how we protect your data.",
            bgImage: "https://res.cloudinary.com/e-commerce-website/image/upload/v1777628788/educa/wewbfb5lhikzedtpbff5.png"
          }
        },
        {
          type: 'RichTextEditor',
          content: {
            title: "CC Electricity App",
            content: "<h2>Introduction</h2><p>Welcome to the CC Electricity App...</p>"
          }
        },
        { type: 'Footer', order: 999 }
      ]
    }
  ];

  for (const p of pagesData) {
    let page = await prisma.page.findUnique({ where: { slug: p.slug } });
    if (!page) {
      page = await prisma.page.create({ data: { name: p.name, slug: p.slug } });
      let currentOrder = 0;
      
      for (const sectionEntry of p.sections) {
        const isString = typeof sectionEntry === 'string';
        const section = sectionEntry as any;
        const type = isString ? sectionEntry : section.type;
        const isVisible = isString ? true : (section.isVisible !== undefined ? section.isVisible : true);
        const order = isString ? currentOrder++ : (section.order !== undefined ? section.order : currentOrder++);
        const content = isString ? getContent(type, p.name) : (section.content || getContent(type, p.name));

        await prisma.section.create({
          data: {
            type,
            pageId: page.id,
            variation: 'style1',
            isVisible,
            order,
            content: content as any
          }
        });
      }
      console.log(`✅ Created page ${p.name}`);
    }
  }

  // 4. Initial Publish Deployment
  const config = await prisma.siteConfig.findUnique({ where: { id: 'default-config' } });
  const allPages = await prisma.page.findMany({ include: { sections: { orderBy: { order: 'asc' } } } });
  
  await prisma.publishedDeployment.upsert({
    where: { id: 'live' },
    update: { data: { config, pages: allPages } },
    create: {
      id: 'live',
      data: { config, pages: allPages }
    }
  });

  console.log('✅ Initial site published to "live" deployment');
  console.log('\n🎉 Seeding complete!');
}

if (require.main === module) {
  main()
    .catch((e) => { console.error('❌ Seed failed:', e); process.exit(1); })
    .finally(async () => { await prisma.$disconnect(); });
}

